### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kiwicopple** [aivantg/airtable-schema-generator#35]
Hey, thanks for this repo. I checked it out and it's awesome.

I have a different use case: I just want to dump everything into SQL files and your repo gives me a lot of the functionality I need. I wanted to check if it's OK to fork and modify your code. I don't think you will want many of my edits, as I want to pull out a lot of the code which I don't need (CRUD helpers)

Is this MIT licensed? Either way, I'll link back to this repo in my readme

**Comment by kiwicopple** [comment]
Oh and full disclosure, this is for [supabase.io](https://supabase.io): https://github.com/supabase

**Comment by aivantg** [comment]
Thanks for pointing out the lack of license! I'm glad you've find a use for it, and you are definitely free to use it under the MIT License. Good luck with your project!

**Comment by kiwicopple** [comment]
Thanks @aivantg 🙏
