### ISSUE TITLE
get__ByIds doesnt seems to work

### ISSUE THREAD

**Issue by romainquellec** [aivantg/airtable-schema-generator#42]
Hello ! 
Thanks for the work done here.

I'm using get__ById and get__ByIds methods, but it seems the first one is working fine, but not the last one. One workaround was to create a new field at the end of the table called id with a special formula RECORD_ID(), but it seems wrong (Especially with get_byId working)

Any feedback of this ?

My error : error: "INVALID_FILTER_BY_FORMULA", message: "The formula for filtering records is invalid: Unknown field names: id()

Thanks.

**Comment by romainquellec** [comment]
Ok, I found it :

`let formula = OR(${ids.reduce((f, id) => `${f} {ID}='${id}',`, '')} 1 < 0);`
in request.js should be :

`let formula = OR(${ids.reduce((f, id) => `${f} RECORD_ID()='${id}',`, '')} 1 < 0);`

**Comment by annieyro** [comment]
Hey @romainquellec, thanks for the catch! The Airtable bases we initially used this with followed a convention where we created special `id` columns using the formula `RECORD_ID()` which is why we didn't notice this bug. I'll update it now.

**Comment by romainquellec** [comment]
Any news ?
